name: $(Build.BuildId)

trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: DEFRA-COMMON-WINDOWS-SSV3

stages:
- stage: DEV
  jobs:
  - job: DeployADF
    steps:
    - checkout: self
    - task: AzurePowerShell@5
      displayName: Deploy ADF Artifacts
      inputs:
        azureSubscription: AZR-BSE-DEV1
        ScriptType: FilePath
        ScriptPath: scripts/Deploy-AdfObjects.ps1
        ScriptArguments: >
          -ResourceGroupName devbseinfrarg01
          -DataFactoryName devbsedatafactory01
        azurePowerShellVersion: LatestVersion
