name: $(Build.BuildId)

trigger:
  branches:
    include:
      - main

pr: none

pool:
  name: DEFRA-COMMON-WINDOWS-SSV3

variables:

- name: project
  value: 'BSE'
- name: ncFunctionInfrastructure
  value: 'INF'
- name: ncResourceGroup
  value: 'RG'
- name: ncDataFactory
  value: 'ADF'
- name: ncKeyVault
  value: 'KV'
- name: ncSqlServer
  value: 'SQ'
- name: subscriptionNumber
  value: '1'
- name: regionNumber
  value: '4'
- name: instanceNumber
  value: '01'

stages:

- stage: DEV
  displayName: Deploy DEV
  variables:
  - name: resourceGroupName
    value: DEV${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncResourceGroup }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  - name: dataFactoryName
    value: DEV${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncDataFactory }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  - name: keyVaultName
    value: DEV${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncKeyVault }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  - name: rdsServerName
    value: 'tses.data.dev1.dev.cerespfm.cloud'
  - name: serviceConnection
    value: AZR-${{ variables.project }}-DEV${{ variables.subscriptionNumber }}
  - name: sqlServerName
    value: DEV${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncSqlServer }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  jobs:
  - deployment: DeployADFDEV
    displayName: Deploy ADF to DEV
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzurePowerShell@5
            displayName: Deploy ADF Artifacts
            inputs:
              azureSubscription: ${{ variables.serviceConnection }}
              ScriptType: FilePath
              ScriptPath: scripts/Deploy-AdfObjects.ps1
              ScriptArguments: >
                -ResourceGroupName "$(resourceGroupName)"
                -DataFactoryName "$(dataFactoryName)"
                -KeyVaultName "$(keyVaultName)"
                -RdsServerName "$(rdsServerName)"
                -SqlServerName "$(sqlServerName)"
              azurePowerShellVersion: LatestVersion

- stage: TST
  displayName: Deploy TST
  dependsOn: DEV
  variables:
  - name: resourceGroupName
    value: TST${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncResourceGroup }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  - name: dataFactoryName
    value: TST${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncDataFactory }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  - name: keyVaultName
    value: TST${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncKeyVault }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  - name: rdsServerName
    value: 'tses.data.dev1.dev.cerespfm.cloud'
  - name: serviceConnection
    value: AZR-${{ variables.project }}-TST${{ variables.subscriptionNumber }}
  - name: sqlServerName
    value: TST${{ variables.project }}${{ variables.ncFunctionInfrastructure }}${{ variables.ncSqlServer }}${{ variables.subscriptionNumber }}${{ variables.regionNumber }}${{ variables.instanceNumber }}
  jobs:
  - deployment: DeployADFTST
    displayName: Deploy ADF to TST
    environment: TST
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzurePowerShell@5
            displayName: Deploy ADF Artifacts
            inputs:
              azureSubscription: ${{ variables.serviceConnection }}
              ScriptType: FilePath
              ScriptPath: scripts/Deploy-AdfObjects.ps1
              ScriptArguments: >
                -ResourceGroupName "$(resourceGroupName)"
                -DataFactoryName "$(dataFactoryName)"
                -KeyVaultName "$(keyVaultName)"
                -RdsServerName "$(rdsServerName)"
                -SqlServerName "$(sqlServerName)"
              azurePowerShellVersion: LatestVersion
          
- stage: PRE
  displayName: Deploy PRE
  dependsOn: TST
  jobs:
  - deployment: DeployADFPRE
    displayName: Deploy ADF to PRE
    environment: PRE
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzurePowerShell@5
            displayName: Deploy ADF Artifacts
            inputs:
              azureSubscription: AZR-BSE-PRE1
              ScriptType: FilePath
              ScriptPath: scripts/Deploy-AdfObjects.ps1
              ScriptArguments: >
                -ResourceGroupName "$(preResourceGroupName)"
                -DataFactoryName "$(preDataFactoryName)"
              azurePowerShellVersion: LatestVersion
